### ISSUE TITLE
Add option to disable selected plugins in Spark via Client Control

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-clientControl-plugin#4]
...Migrated from [Ignite Jira OF-1372](https://issues.igniterealtime.org/browse/OF-1372)...

It would be useful and more convenient to disable some plugins via a separate settings page in Client Control plugin, instead of modifying default.properties inside spark.jar or altering spark.properties file for every use (which can still be circumvented).

Not sure how this can be implemented as there won't be an easy way to get the list of all available plugins for Spark in Openfire's Admin Console. Maybe it should just provide a text box for admin to type in names of plugins (one can find them in the list of plugins in Spark). Similarly it is done in spark.properties or default.properties file. But this can clash with the current implementation, which should be altered/updated too probably.

**Comment by guusdk** [comment]
Related Spark functionality change is tracked in https://igniterealtime.atlassian.net/browse/SPARK-2005
